### ISSUE TITLE
Paths under Windows for fmus

### ISSUE THREAD

**Issue by RuedKamp** [omuses/hqp#6]
The are still error for the fmu binaries path under Windows, although there were some fixes with the commit:
Fix pathes for FMI binaries under Win64 and LPSolve under Linux
73fe831c8311b791cd9b782b29f1978c97fc0f17

It seems to work for discrete problems but not for continous ones.
See the attached output of the mingw console:
Unfortunately it was not possible to upload it as screenshot.

kar2lo@LO-X18002 MINGW64 /d/Programs/HQP/hqp/odc
$ tclsh did_fmu.tcl
Running optimization...
 it          obj    ||inf||   ||grdL|| [ qp res]      ||s||       s'Qs stepsize
  0            4       0.15    0.06667 [ 19 opt]      4.488      9.792        1
  1      8.89576 1.011e-010 4.488e-008
                                         19 qp-it
Result   : optimal
Objective: 8.895757226232119
Obj-evals: 1
Plotting resulting signals...
Skipping plot as no blt::graph available.

kar2lo@LO-X18002 MINGW64 /d/Programs/HQP/hqp/odc
$ tclsh dic_fmu.tcl
Running optimization...
./.DIC/binaries/win32/DIC.dllerror invoking prg_setup_stages: LoadLibrary failed for FMU
    while executing
"prg_setup_stages"
    (file "dic_fmu.tcl" line 31)
Error from mdlInitializeSizes: LoadLibrary failed for FMU

**Comment by rfranke** [comment]
Does the issue still exist?
There is no good reason why the `did_fmu` works and `dic_fmu` not. Maybe a compiler flag in OpenModelica that causes an additional link dependency for the latter? Did you check `binaries/win64/dic_fmu.dll` with `depends`?
