### ISSUE TITLE
Comparisons with other free solvers

### ISSUE THREAD

**Issue by freemin7** [omuses/hqp#8]
Hello,

i've been working to make the Worhp solver (free for academics/testing) available as an NLP backend in the JuMP ecosystem.
Recently i discovered the existence of this package.
Do you suspect this package being competitive with Ipopt or Worhp when given access to the function, the gradient, the jacobian and hessian and the sparsity structures of the jacobian and hessian?

I am aware that his package offers more then just an NLP (or QP) solver however there is no standardized interface for the optimization of dynamic problems in Julia yet. So my interest in making those features available is limited for now.

Sincerely,
Johann-Tobias Schäg,
Student, I.-A., TU Ilmenau

**Comment by rfranke** [comment]
HQP contains interfaces to CUTE and ASCEND. It has been tested extensively with the former. The strength of this package is the formulation of optimization programs basing on simulation models via FMI interface.

A Julia interface sounds interesting. Maybe leveraging something like Modia?

**Comment by freemin7** [comment]
I am currently in my exam phase which is why i didn't reply.
